### ISSUE TITLE
node fails to start nginx randomly 

### ISSUE THREAD

**Issue by ropolexi** [bitclout/run#47]
The node fails to start sometimes. I think nginx shoud be started after starting frontend.
Here is the log 
```
nginx       | 2021/05/09 13:41:54 [emerg] 1#1: host not found in upstream "frontend" in /etc/nginx/nginx.conf:10
nginx       | nginx: [emerg] host not found in upstream "frontend" in /etc/nginx/nginx.conf:10
nginx exited with code 1
```

**Comment by tijno** [comment]
Sorry above was messy PR - resubmitted #49 

@ropolexi you should be able to solve it by adding a `depends_on:` section, so the nginx bit looks like this:

```
nginx: 
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx.dev:/etc/nginx/nginx.conf
    depends_on: 
      - core
      - frontend
    ports:
      - 80:80
      - 443:443
```
